// src/components/countriesList.js
// 🌍 Lista completa de países com nome em português + código ISO (Alpha-2)
export const countries = [
  { code: "AF", name: "Afeganistão" },
  { code: "AL", name: "Albânia" },
  { code: "DZ", name: "Argélia" },
  { code: "AS", name: "Samoa Americana" },
  { code: "AD", name: "Andorra" },
  { code: "AO", name: "Angola" },
  { code: "AI", name: "Anguila" },
  { code: "AQ", name: "Antártida" },
  { code: "AG", name: "Antígua e Barbuda" },
  { code: "AR", name: "Argentina" },
  { code: "AM", name: "Arménia" },
  { code: "AW", name: "Aruba" },
  { code: "AU", name: "Austrália" },
  { code: "AT", name: "Áustria" },
  { code: "AZ", name: "Azerbaijão" },
  { code: "BS", name: "Bahamas" },
  { code: "BH", name: "Barém" },
  { code: "BD", name: "Bangladesh" },
  { code: "BB", name: "Barbados" },
  { code: "BY", name: "Bielorrússia" },
  { code: "BE", name: "Bélgica" },
  { code: "BZ", name: "Belize" },
  { code: "BJ", name: "Benim" },
  { code: "BM", name: "Bermudas" },
  { code: "BT", name: "Butão" },
  { code: "BO", name: "Bolívia" },
  { code: "BA", name: "Bósnia e Herzegovina" },
  { code: "BW", name: "Botsuana" },
  { code: "BR", name: "Brasil" },
  { code: "BN", name: "Brunei" },
  { code: "BG", name: "Bulgária" },
  { code: "BF", name: "Burquina Fasso" },
  { code: "BI", name: "Burundi" },
  { code: "CV", name: "Cabo Verde" },
  { code: "KH", name: "Camboja" },
  { code: "CM", name: "Camarões" },
  { code: "CA", name: "Canadá" },
  { code: "CF", name: "República Centro-Africana" },
  { code: "TD", name: "Chade" },
  { code: "CL", name: "Chile" },
  { code: "CN", name: "China" },
  { code: "CO", name: "Colômbia" },
  { code: "KM", name: "Comores" },
  { code: "CG", name: "Congo" },
  { code: "CD", name: "República Democrática do Congo" },
  { code: "CR", name: "Costa Rica" },
  { code: "HR", name: "Croácia" },
  { code: "CU", name: "Cuba" },
  { code: "CY", name: "Chipre" },
  { code: "CZ", name: "Chéquia" },
  { code: "DK", name: "Dinamarca" },
  { code: "DJ", name: "Djibuti" },
  { code: "DM", name: "Domínica" },
  { code: "DO", name: "República Dominicana" },
  { code: "EC", name: "Equador" },
  { code: "EG", name: "Egito" },
  { code: "SV", name: "El Salvador" },
  { code: "GQ", name: "Guiné Equatorial" },
  { code: "ER", name: "Eritreia" },
  { code: "EE", name: "Estónia" },
  { code: "SZ", name: "Essuatíni" },
  { code: "ET", name: "Etiópia" },
  { code: "FJ", name: "Fiji" },
  { code: "FI", name: "Finlândia" },
  { code: "FR", name: "França" },
  { code: "GA", name: "Gabão" },
  { code: "GM", name: "Gâmbia" },
  { code: "GE", name: "Geórgia" },
  { code: "DE", name: "Alemanha" },
  { code: "GH", name: "Gana" },
  { code: "GR", name: "Grécia" },
  { code: "GD", name: "Granada" },
  { code: "GT", name: "Guatemala" },
  { code: "GN", name: "Guiné" },
  { code: "GW", name: "Guiné-Bissau" },
  { code: "GY", name: "Guiana" },
  { code: "HT", name: "Haiti" },
  { code: "HN", name: "Honduras" },
  { code: "HU", name: "Hungria" },
  { code: "IS", name: "Islândia" },
  { code: "IN", name: "Índia" },
  { code: "ID", name: "Indonésia" },
  { code: "IR", name: "Irão" },
  { code: "IQ", name: "Iraque" },
  { code: "IE", name: "Irlanda" },
  { code: "IL", name: "Israel" },
  { code: "IT", name: "Itália" },
  { code: "JM", name: "Jamaica" },
  { code: "JP", name: "Japão" },
  { code: "JO", name: "Jordânia" },
  { code: "KZ", name: "Cazaquistão" },
  { code: "KE", name: "Quénia" },
  { code: "KR", name: "Coreia do Sul" },
  { code: "KW", name: "Kuwait" },
  { code: "LA", name: "Laos" },
  { code: "LV", name: "Letónia" },
  { code: "LB", name: "Líbano" },
  { code: "LS", name: "Lesoto" },
  { code: "LR", name: "Libéria" },
  { code: "LY", name: "Líbia" },
  { code: "LT", name: "Lituânia" },
  { code: "LU", name: "Luxemburgo" },
  { code: "MG", name: "Madagáscar" },
  { code: "MW", name: "Maláui" },
  { code: "MY", name: "Malásia" },
  { code: "MV", name: "Maldivas" },
  { code: "ML", name: "Mali" },
  { code: "MT", name: "Malta" },
  { code: "MX", name: "México" },
  { code: "MD", name: "Moldávia" },
  { code: "MC", name: "Mónaco" },
  { code: "MN", name: "Mongólia" },
  { code: "ME", name: "Montenegro" },
  { code: "MA", name: "Marrocos" },
  { code: "MZ", name: "Moçambique" },
  { code: "NA", name: "Namíbia" },
  { code: "NP", name: "Nepal" },
  { code: "NL", name: "Países Baixos" },
  { code: "NZ", name: "Nova Zelândia" },
  { code: "NI", name: "Nicarágua" },
  { code: "NE", name: "Níger" },
  { code: "NG", name: "Nigéria" },
  { code: "NO", name: "Noruega" },
  { code: "OM", name: "Omã" },
  { code: "PK", name: "Paquistão" },
  { code: "PA", name: "Panamá" },
  { code: "PG", name: "Papua-Nova Guiné" },
  { code: "PY", name: "Paraguai" },
  { code: "PE", name: "Peru" },
  { code: "PH", name: "Filipinas" },
  { code: "PL", name: "Polónia" },
  { code: "PT", name: "Portugal" },
  { code: "QA", name: "Catar" },
  { code: "RO", name: "Roménia" },
  { code: "RU", name: "Rússia" },
  { code: "RW", name: "Ruanda" },
  { code: "SA", name: "Arábia Saudita" },
  { code: "SN", name: "Senegal" },
  { code: "RS", name: "Sérvia" },
  { code: "SC", name: "Seicheles" },
  { code: "SL", name: "Serra Leoa" },
  { code: "SG", name: "Singapura" },
  { code: "SK", name: "Eslováquia" },
  { code: "SI", name: "Eslovénia" },
  { code: "ZA", name: "África do Sul" },
  { code: "ES", name: "Espanha" },
  { code: "LK", name: "Sri Lanca" },
  { code: "SD", name: "Sudão" },
  { code: "SE", name: "Suécia" },
  { code: "CH", name: "Suíça" },
  { code: "SY", name: "Síria" },
  { code: "TW", name: "Taiwan" },
  { code: "TZ", name: "Tanzânia" },
  { code: "TH", name: "Tailândia" },
  { code: "TG", name: "Togo" },
  { code: "TT", name: "Trindade e Tobago" },
  { code: "TN", name: "Tunísia" },
  { code: "TR", name: "Turquia" },
  { code: "UG", name: "Uganda" },
  { code: "UA", name: "Ucrânia" },
  { code: "AE", name: "Emirados Árabes Unidos" },
  { code: "GB", name: "Reino Unido" },
  { code: "US", name: "Estados Unidos" },
  { code: "UY", name: "Uruguai" },
  { code: "UZ", name: "Usbequistão" },
  { code: "VE", name: "Venezuela" },
  { code: "VN", name: "Vietname" },
  { code: "YE", name: "Iémen" },
  { code: "ZM", name: "Zâmbia" },
  { code: "ZW", name: "Zimbábue" },
];
